# 前情提要
前陣子在一門教文組用JAVA寫程式的課堂裡，出現了一題挑戰題，要我們在得到輸入的n之後，輸出一個類似螺旋向內的矩陣，形如：

７　８　１　　　　　　１０　１１　１２　　１

６　９　２　　或是　　　９　１６　１３　　２

５　４　３　　　　　　　８　１５　１４　　３

　　　　　　　　　　　　７　　６　　５　　４


教授口口聲聲說著這個很難，網路上的解法用了四層的while什麼的....

...

可是我覺得不用啊？

基於一種題目難度被跨大的憤慨(?)，我決定來實際解決他，用感覺很笨的方法。


順帶一題，這種矩陣如果應用在讓畫面逐漸變黑的順序，就可以做出早期神奇寶貝遭遇戰的過場喔。(喔！！！！！)

好，總之我們的計畫很簡單，用一台壓路機(X)編號機從左上角開始走，走到一定的距離(或是碰壁)就順時針轉彎，直到把所有編號用完。
首先處理你想要產生多大的繞圈圈矩陣(對，它從現在開始叫這個名字了)

In [70]:
import numpy as np
import pandas as pd

print('請問您今天想要多大的繞圈圈矩陣呢？')
mysize = int(input("我要："))

field = np.zeros((mysize, mysize))

請問您今天想要多大的繞圈圈矩陣呢？
我要：10


(其實這根本用不到pandas，但我還是引入了，因為我覺得這樣很cool)

接著我們來定義方向吧！把上下左右四個方向存在一個陣列裡面，順時針轉彎就是變成陣列下一個元素!
另外還有表示目前位子的current_place以及編到第幾號的count。

In [71]:
directions = {0:[1, 0], 1:[0, -1], 2:[-1, 0], 3:[0, 1]}
current_direction = 0
current_place = np.array([0, mysize-1])
count = 1

接著就能開始走囉!

透過觀察得知，從左上角為起點，mysize為大小的話，我們前三次都會先走(mysize-1)的距離再轉彎，接著只會走(mysize-2)的距離就要轉彎，兩次後變成(mysize-3)，兩次後再減少...秉持著這個精神就可以寫出來了!!

In [72]:
#先編號腳下這格
field[current_place[0], current_place[1]] = count
count = count + 1

#走一步編一次號，先把第一條邊走完
for i in range(0, mysize-1):
    current_place = current_place + directions[current_direction]
    field[current_place[0], current_place[1]] = count
    count = count + 1
    
for i in range(0, mysize-1):
    for L in range(0,2):
        #轉彎
        current_direction = (current_direction + 1) % 4    
        for j in range(0, mysize-1-i):
            #走一條
            current_place = current_place + directions[current_direction]
            field[current_place[0], current_place[1]] = count
            count = count + 1
            

這樣就做完了！馬上來看看編號完的矩陣長甚麼樣子吧~

In [73]:
print(field)

[[ 28.  29.  30.  31.  32.  33.  34.  35.  36.   1.]
 [ 27.  58.  59.  60.  61.  62.  63.  64.  37.   2.]
 [ 26.  57.  80.  81.  82.  83.  84.  65.  38.   3.]
 [ 25.  56.  79.  94.  95.  96.  85.  66.  39.   4.]
 [ 24.  55.  78.  93. 100.  97.  86.  67.  40.   5.]
 [ 23.  54.  77.  92.  99.  98.  87.  68.  41.   6.]
 [ 22.  53.  76.  91.  90.  89.  88.  69.  42.   7.]
 [ 21.  52.  75.  74.  73.  72.  71.  70.  43.   8.]
 [ 20.  51.  50.  49.  48.  47.  46.  45.  44.   9.]
 [ 19.  18.  17.  16.  15.  14.  13.  12.  11.  10.]]


是不是很好看呢~


才怪，我忘了怎麼好看的輸出矩陣了= =

不過無須氣餒，我們已經完成了這項創舉!!

為了讓它更動感，我們還可以在每一次填完數字後都清掉一次輸出並再輸出新的矩陣，看到它實際在繞圈圈哦

In [74]:
from IPython.display import clear_output
import time

#初始化
field = np.zeros((mysize, mysize))
current_direction = 0
current_place = np.array([0, mysize-1])
count = 1

print(field)
#然後把上面的東東都複製下來

#先編號腳下這格
field[current_place[0], current_place[1]] = count
count = count + 1

clear_output(wait=True)
print(field)
time.sleep(0.1)

#走一步編一次號，先把第一條邊走完
for i in range(0, mysize-1):
    current_place = current_place + directions[current_direction]
    field[current_place[0], current_place[1]] = count
    count = count + 1
    
    clear_output(wait=True)
    print(field)
    time.sleep(0.1)
    
for i in range(0, mysize-1):
    for L in range(0,2):
        #轉彎
        current_direction = (current_direction + 1) % 4    
        for j in range(0, mysize-1-i):
            #走一條
            current_place = current_place + directions[current_direction]
            field[current_place[0], current_place[1]] = count
            count = count + 1

            clear_output(wait=True)
            print(field)
            time.sleep(0.1)
            

[[ 28.  29.  30.  31.  32.  33.  34.  35.  36.   1.]
 [ 27.  58.  59.  60.  61.  62.  63.  64.  37.   2.]
 [ 26.  57.  80.  81.  82.  83.  84.  65.  38.   3.]
 [ 25.  56.  79.  94.  95.  96.  85.  66.  39.   4.]
 [ 24.  55.  78.  93. 100.  97.  86.  67.  40.   5.]
 [ 23.  54.  77.  92.  99.  98.  87.  68.  41.   6.]
 [ 22.  53.  76.  91.  90.  89.  88.  69.  42.   7.]
 [ 21.  52.  75.  74.  73.  72.  71.  70.  43.   8.]
 [ 20.  51.  50.  49.  48.  47.  46.  45.  44.   9.]
 [ 19.  18.  17.  16.  15.  14.  13.  12.  11.  10.]]


雖然看起來(實際也)很無用，不過看他這樣繞圈圈也是滿有趣的XDDDD
如果應用這個編號當順序的話或許很適合拿來做螺旋的轉場也說不定?